module.exports = [
    {
      title: "Just Go With It",
      movieDescription: "On a weekend trip to Hawaii, a plastic surgeon convinces his loyal assistant to pose as his soon-to-be-divorced wife in order to cover up a careless lie he told to his much-younger girlfriend.",
      movieImg: "https://m.media-amazon.com/images/M/MV5BMTM3MzM3NDE5MV5BMl5BanBnXkFtZTcwNDE5MTUxNA@@._V1_FMjpg_UX1000_.jpg",
      director: "Dennis Dugan",
      cast: "Adam Sandler, Jennifer Aniston, Nicole Kidman",
      opinions: "One of my favorite movies.",
    },
    {
      title: "She's the Man",
      movieDescription: "When her brother decides to ditch for a couple weeks, Viola heads over to his elite boarding school, disguised as him, and proceeds to fall for his school's star soccer player, and soon learns she's not the only one with romantic troubles.",
      movieImg: "https://m.media-amazon.com/images/M/MV5BZGRmNzYxM2QtNGVlZi00ZWZhLWFlMzEtNzE5NGM4YjlkYjY0XkEyXkFqcGdeQXVyMTY5Nzc4MDY@._V1_.jpg",
      director: "Andy Fickman",
      cast: "Amanda Bynes, Channing Tatum, Laura Ramsey",
      opinions: "Love this movie.",
    },
    {
      title: "Miss Congeniality",
      movieDescription: "An F.B.I. Agent must go undercover in the Miss United States beauty pageant to prevent a group from bombing the event.",
      movieImg: "https://m.media-amazon.com/images/M/MV5BZDhjNzc4N2MtNWE5ZC00N2M4LWFiYjEtMTE5YmYyMTg3OGY5XkEyXkFqcGdeQXVyMTkzODUwNzk@._V1_.jpg",
      director: "Donald Petrie",
      cast: "Sandra Bullock, Benjamin Bratt, Michael Caine",
      opinions: "Not really interested.",
    },
    {
      title: "10 Things I Hate About You",
      movieDescription: "A pretty, popular teenager can't go out on a date until her ill-tempered older sister does.",
      movieImg: "https://m.media-amazon.com/images/M/MV5BMmVhZjhlZDYtMDAwZi00MDcyLTgzOTItOWNiZjY0YmE0MGE0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg",
      director: "Gil Junger",
      cast: "Heath Ledger, Julia Stiles, Joseph Gordon-Levitt",
      opinions: "Such a good movie.",
    },
    {
      title: "She's All That",
      movieDescription: "A high school jock makes a bet that he can turn an unattractive girl into the school's prom queen.",
      movieImg: "https://m.media-amazon.com/images/M/MV5BY2Y0N2YyOTQtMGNiYy00ZDViLTgxYmItODkxNzlkMWVjNTFkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
      director: "Robert Iscove",
      cast: "Freddie Prinze Jr., Rachael Leigh Cook, Matthew Lillard, Paul Walker",
      opinions: "Need to rewatch this movie.",
    },
];